### ISSUE TITLE
Remove elements deprecated in 3.0.x

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-addons#79]
- [x] `VirtualTimeScheduler#enable` methods (#70)
- [x] `withVirtualTime(long n, ...)` methods (#38)
- [x] `VirtualTimeScheduler` methods around `enableForAll` (always enable for all) (#95)

**Comment by smaldini** [comment]
Fixed on current 3.1 by https://github.com/reactor/reactor-addons/commit/9251f851723eb811b5faf2c05e2f03c208ccad94
